{{- if (and .Values.captivePortalService.ingress.enabled (not .Values.unifiedService.enabled)) }}
{{- $fullName := include "unifi.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-captive
  {{- with .Values.captivePortalService.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.captivePortalService.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.captivePortalService.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-captiveportalservice
                port:
                  {{- if $.Values.captivePortalService.https }}
                  name: captive-https
                  {{- else }}
                  name: captive-http
                  {{- end }}
    {{- end }}
  {{- if .Values.captivePortalService.ingress.tls }}
  tls:
    {{- range .Values.captivePortalService.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
