{{- if (and .Values.controllerService.ingress.enabled (not .Values.unifiedService.enabled)) }}
{{- $fullName := include "unifi.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-controller
  {{- with .Values.controllerService.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.controllerService.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.controllerService.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-controller
                port:
                  name: controller
    {{- end }}
  {{- if .Values.controllerService.ingress.tls }}
  tls:
    {{- range .Values.controllerService.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
