{{- if and .Values.speedtestService.enabled (not .Values.unifiedService.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "unifi.fullname" . }}-speedtest
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
    {{- if .Values.speedtestService.labels }}
    {{- toYaml .Values.speedtestService.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.speedtestService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if (or (eq .Values.speedtestService.type "ClusterIP") (empty .Values.speedtestService.type)) }}
  type: ClusterIP
  {{- if .Values.speedtestService.clusterIP }}
  clusterIP: {{ .Values.speedtestService.clusterIP }}
  {{- end }}
{{- else if eq .Values.speedtestService.type "LoadBalancer" }}
  type: {{ .Values.speedtestService.type }}
  {{- if .Values.speedtestService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.speedtestService.loadBalancerIP }}
  {{- end }}
  {{- if .Values.speedtestService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.speedtestService.loadBalancerSourceRanges | nindent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.speedtestService.type }}
{{- end }}
  {{- if .Values.speedtestService.externalIPs }}
  externalIPs:
    {{- toYaml .Values.speedtestService.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.speedtestService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.speedtestService.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.speedtestService.port }}
      targetPort: speedtest
      protocol: TCP
      name: speedtest
      {{- if (and (eq .Values.speedtestService.type "NodePort") (not (empty .Values.speedtestService.nodePort))) }}
      nodePort: {{.Values.speedtestService.nodePort}}
      {{- end }}
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
{{- end }}
