## Reference: https://github.com/pascalgn/size-label-action
name: 'PR Labeling'

on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@be08a2d5f857dc99c5b9426cdb5a8ea1aa7f0399 # v0.5.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
